# -*- coding: utf-8 -*-
"""ETL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oewkPfBdmgPQGx-hlV3lo4Og8-eGW4Q
"""

import pandas as pd
import numpy as np
import requests
from io import StringIO

# Extraer desde una URL
url = 'https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv'
response = requests.get(url)
data = StringIO(response.text)
df = pd.read_csv(data)

# Ver los primeros datos
df.head()

# Renombrar columnas
df.columns = ['Index', 'Height(Inches)', 'Weight(Pounds)', 'Extra Column']


df['Height(m)'] = df['Height(Inches)'] * 0.0254   # Pulgadas a metros
df['Weight(kg)'] = df['Weight(Pounds)'] * 0.453592  # Libras a kilogramos

# Filtrar personas con altura mayor a 1.60 metros
df_filtered = df[df['Height(m)'] > 1.60]

# Ver el resultado
df_filtered.head()

# Guardar a CSV
df_filtered.to_csv('filtered_data.csv', index=False)

# Descargar en Colab
from google.colab import files
files.download('filtered_data.csv')